version = 0.1
[default.deploy.parameters]
stack_name = "e2e-demo-cloudformation"
resolve_s3 = true
s3_prefix = "e2e-demo-cloudformation"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "SourceBucketName=\"origin-bucket\" QueueName=\"origin-sqs\" DestinationBucketName=\"destination-bucket\" QueueDestinationName=\"destination-sqs\""
image_repositories = []
